### PR TITLE
Fix docker image labels

### PR DESCRIPTION
**Pull request by petrovicboban**

### CODE REVIEW

**Comment by edwardwliu** [comment]
Fix LGTM, you can tag @theo-s for explicit review.

@petrovicboban Would it be simple to create a Docker image for the R [package](https://github.com/forestry-labs/Rforestry/blob/master/.github/workflows/check-noncontainerized.yaml) or the same image for both? I'm open to your thoughts on best practices here, but also wonder the historical reason of why we switched away from containerized [builds](https://github.com/forestry-labs/Rforestry/commit/e88acb352df123d35eba764e649a6ae8791d425f).

**Comment by petrovicboban** [comment]
The image we are building here is image to be used in python build pipeline. We are already using docker container to build linux python packages, from publicly available images, but those images doesn't have some dependencies we need for build time (armadillo libs, R, etc). In order to speed up build time, we make our own docker image for python build environment with everything we need.

Later, when we finish merging cpp changes and when we start publishing Python packages, we will also build docker images with Python and built package in it, ready to be used. Probably the same for R.

**Comment by edwardwliu** [comment]
I understand, was asking if we wanted to migrate the build pipeline for the R package to a custom Docker image as well. However, I realize that's tangential to this PR so we can move this discussion to the `forestry-labs` repo.

**Comment by petrovicboban** [comment]
R pipeline doesn't run in container. Also Python doesn't too. It uses docker container only to build linux packages in order to build `manylinux` compatible packages (as described here https://cibuildwheel.readthedocs.io/en/stable/faq/)

**Review by theo-s — APPROVED** [review]
Thanks for explaining this. Merging this in now, for future discussion on this, we can move to the `forestry-labs` repo

**Pull request merged**
