### PR TITLE
Merge upstream changes in forestry-labs to fork

### PR DESCRIPTION
**Pull request by edwardwliu**
Only updates files that should not affect the Python build.

### CODE REVIEW

**Comment by edwardwliu** [comment]
@theo-s (cc @petrovicboban) Creating a PR merging forestry-labs changes to non-Python dependent files in to the fork. It looks like just one [test](https://github.com/theo-s/Rforestry/actions/runs/4326730796/jobs/7554499455#step:9:173) is failing. I remember you mentioned changes related to the order of nodes. Do you have insights here (also unsure why it only passes in some other builds)? Also open to merging in this PR and addressing the failing test separately.

**Comment by theo-s** [comment]
Hi Edward, thanks for creating this PR. It looks like the test failing is for terminal nodes, which definitely will change with the new numbering scheme of nodes. In a gist, previous versions of the C++ code (that these R tests rely on), only gave Node ID's to leaf nodes, while now to standardize the code and support features such as `decision_path`, both leaf and split nodes are given Node IDs. So this should change the output of terminalNodes in R.

**Comment by edwardwliu** [comment]
I updated the test so we got a clean build of the R package (using `#include <RcppArmadillo.h>` instead of `#include <armadillo>` in `rcpp_cppBuildInterface.cpp` / `RcppExports.cpp`). I don't want the Python build to fail in this fork, so I removed `#include<RcppArmadillo.h>` from this PR again. 

@theo-s When you get the chance, could you approve and merge in this PR? It should resolve most R package specific merge conflicts between the fork master and forestry-labs master branch. 

I've also updated the Kanban [board](https://github.com/orgs/forestry-labs/projects/1). The primary outcome is to land a clean build of the R and Python packages in `forestry-labs`. Two sub-items are moving `RppArmadillo` outside of the shared `src/` and checking the terminal nodes implementation in R. We should aim for a successful build of both packages by next week since we want to leave some buffer for release. It would be great for @petrovicboban to continue pushing this forward. I'll alsoa follow-up over email so we hopefully have a quick sync meeting Monday/Tuesday.

**Comment by edwardwliu** [comment]
@theo-s (cc @petrovicboban) Uses `#include <RcppArmadillo.h>` per our discussion. The R package is now successfully building in this repo so we should be able to merge this in.

**Review by theo-s — APPROVED** [review]
Thanks for changing this, looks like that was good enough to get the R build passing

**Pull request merged**
