### PR TITLE
Add github action to lint cpp files

### PR DESCRIPTION
**Pull request by petrovicboban**

### CODE REVIEW

**Comment by edwardwliu** [comment]
Thanks for this Boban. Are you able to create an example PR or branch with the `clang-tidy` check enabled? I'm a little concerned about noise from the number of warnings generated. We may want to suppress some and address them gradually over time. 

As a follow-up, what's your recommended approach for addressing the warnings? Is this something you'd like to work through? Maybe we can take a look at an example branch after running `--fix` and determine if we'd like to invest time in fixing valuable warnings one by one.

**Comment by petrovicboban** [comment]
I'm not C++ developer, so I don't hold clang-tidy as the best linter out there. It's just the one I found out there which has good reviews. If you recommend other linter to use, I'm open for suggestions.

As every other linter, this one produces messages in different severities (error, warning, note). If there is at least one error message, exit code is non-zero, which makes pipeline to fail. Warnings and notes doesn't affect pipeline success, and they are there only for developer to have insight.
Other than option to treat warnings as errors, and select checks to perform/ignore, I couldn't find other meaningful options we could use in pipeline. I was thinking about suppressing notes, but it doesn't seem possible. However, there seems to be option to add comment in source code line (`#NOLINT` or something like that) in order to ignore warning/note on it.

**Comment by edwardwliu** [comment]
If it's difficult to generate an example branch, I'm okay with merging this in then evaluating the raised warnings. If we deem it too noisy, we can then decide if a less approach would be more appropriate. Will wait for @theo-s's thoughts on enabling linting.

**Comment by petrovicboban** [comment]
I don't understand what would you try to do with that branch you want. If you want it, Theo can create branch from current master, and I can create PR to it with clang-tidy

**Comment by theo-s** [comment]
@petrovicboban Thank you for setting up code linting. I do think we should enable linting by default, having the check fail on an error, but pass on warnings + notes seems acceptable. Also we may want to choose the exact flags given to `clang-tidy` and also choose a style guide to check the project against. I propose the [Google C++ style guide](https://google.github.io/styleguide/cppguide.html) since `clang-tidy` supports a check for this, if either of you have ideas here, let me know. For now I will merge this into master and then we can decide what arguments to use for the linting going forward.

P.S. `clang-tidy` is integrated into several IDE's if you want to check files before committing to Github. Looking at the project on CLion I see a large number of warnings listed

**Review by theo-s — APPROVED** [review]
Merging into master

**Pull request merged**
